code --install-extension azemoh.one-monokai
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cschleiden.vscode-github-actions
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension eamodio.gitlens
code --install-extension EasyMock.easymock
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension exiasr.hadolint
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.auto-rename-tag
code --install-extension KevinRose.vsc-python-indent
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension snakemake.snakemake-lang
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
